#!/usr/bin/env bash

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a custom 404 HTML page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx
